name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update 
        sudo apt-get install allure

    - name: Run tests
      run: |
        export PYTHONPATH="$PWD/src"
        pytest --alluredir=./allure_testing_reports

    - name: List contents of current working directory
      run: |
        ls -la

    - name: Upload allure testing reports
      uses: actions/upload-artifact@v2
      with:
        name: allure_reports
        path: ./allure_testing_reports
